import { IColumnList } from './positions-table/types/IColumnList';

export const ColumnList: IColumnList[] = [
  {
    name: 'id',
    key: 'id',
    type: 'string',
    classHeader: 'hidden',
    classColumn: 'hidden',
    classFooter: 'hidden',
  },
  {
    name: 'KOLEJNOSC',
    key: 'kolejnosc',
    type: 'string',
    classHeader: 'hidden',
    classColumn: 'hidden',
    classFooter: 'hidden',
  },
  {
    name: 'ZDJĘCIE',
    key: 'image',
    type: 'image',
    pdfWidth: 60,
  },
  {
    name: 'PRODUKT',
    key: 'produkt',
    type: 'textarea',
    pdfWidth: 50,
  },
  {
    name: 'PRODUCENT',
    key: 'producent',
    type: 'textarea',
    pdfWidth: 50,
  },
  {
    name: 'KOLEKCJA/SERIA',
    key: 'kolekcja',
    type: 'textarea',
    pdfWidth: 70,
  },
  {
    name: 'NR KATALOGOWY',
    key: 'nrKatalogowy',
    type: 'textarea',
    pdfWidth: 70,
  },
  {
    name: 'KOLOR',
    key: 'kolor',
    type: 'textarea',
    pdfWidth: 40,
  },
  {
    name: 'ILOŚĆ',
    key: 'ilosc',
    type: 'number',
    pdfWidth: 20,
  },
  {
    name: 'CENA NETTO',
    key: 'netto',
    type: 'number',
    pdfWidth: 30,
  },
  {
    name: 'CENA BRUTTO',
    key: 'brutto',
    type: 'number',
    pdfWidth: 30,
  },
  {
    name: 'WARTOŚĆ NETTO',
    key: 'wartoscNetto',
    type: 'number',
    readOnly: true,
    classColumn: 'read-only',
    pdfWidth: 40,
  },
  {
    name: 'WARTOŚĆ BRUTTO',
    key: 'wartoscBrutto',
    type: 'number',
    readOnly: true,
    classColumn: 'read-only',
    pdfWidth: 40,
  },
  {
    name: 'DOSTAWCA',
    key: 'supplierId',
    type: 'select',
    classColumn: 'select-field',
    optionList: 'allSuppliers',
    optionLabel: 'company',
    pdfWidth: 50,
  },
  {
    name: 'POMIESZCZENIE',
    key: 'pomieszczenie',
    type: 'textarea',
    pdfWidth: 60,
  },
  {
    name: 'LINK',
    key: 'link',
    type: 'link',
    pdfWidth: 30,
  },
  {
    name: 'STATUS',
    key: 'status',
    type: 'select',
    classColumn: 'select-field',
    optionList: 'positionStatus',
    optionLabel: 'label',
    pdfWidth: 45,
  },
  {
    name: 'UWAGI',
    key: 'uwagi',
    type: 'textarea',
  },
];
